/**
 * Frontend-inngang til den delte kontrakten mellom HUD og Jarvis-backend.
 * Én kilde til sannhet: agent/lib/contract.mjs (+ contract.d.ts).
 */
export {
  API_VERSION,
  CONFIG_BUNDLE_VERSION,
  CONFIG_DOCS,
  RULE_OPERATORS,
  RULE_ACTION_TYPES,
  USER_ROLES,
  ROUTES,
  NODE_DUTIES,
  NODE_DUTY_LABELS,
  SETTINGS_SCHEMA,
  SETTINGS_DEFAULTS,
  validateNode,
  validateSettings,
  ERROR_CODES,
  ERROR_TEXTS,
  DEFAULTS,
  validateRule,
  validateCredentials,
  codeFromStatus,
} from "../../agent/lib/contract.mjs";

export type {
  AiChatReply,
  AiConfig,
  BackendSettings,
  ClusterNode,
  MqttHealth,
  NodeDuty,
  SettingsField,
  SettingsGroup,
  BackendRule,
  BackendStatus,
  BackendUser,
  BackupFile,
  ErrorCode,
  KnowledgeDoc,
  KnowledgeHit,
  ClusterHealth,
  DistributeResult,
  GpuStatus,
  HealthLevel,
  LogSource,
  LogTail,
  NodeHealth,
  NodeSnapshot,
  TtsConfig,
  VoiceClip,
  RagConfig,
  MqttConfig,
  MqttStatus,
  PoolNode,
  PoolStatus,
  RuleAction,
  RuleActionType,
  RuleEvent,
  RuleOperator,
  RulesStatus,
  Sample,
  SampleSummary,
  TelegramConfig,
  ThreadSummary,
  UserRole,
} from "../../agent/lib/contract.mjs";
